Hooks:PostHook( WeaponTweakData, "init", "Tact_Reload", function(self)	
	--tactical reloading shite
	local tact_rel = {
		-- SMGs --
		"hajk", --"CZ 805 BREN A1"
		"polymer", --"KRISS Vector"
		"m1928", --"Thompson M1928A1"
		"schakal", --"H&K UMP-45"
		"new_mp5", --"H&K MP5A4"
		"sr2", --"SR-2M Veresk"
		"sterling", --"Sterling L2A1"
		"m45", --"Carl Gustav M/45"
		"uzi", --"IMI Uzi"
		"baka", --"IMI Micro Uzi"
		"scorpion", --"Scropion vz.61"
		"mp9", --"B&T MP9"
		"mac10", --"Ingram MAC-10"
		"cobray", --"Cobray M11/9"
		"mp7", --"H&K MP7A2"
		"p90", --"FN P90 TR"
		"coal", --"PP-19 Bizon"
		"tec9", --"Intratec TEC-9"
		"erma", --"MP40"
		"shepheard", --"SIG-Sauer MPX"
		-- AR15s/HK416 --
		"olympic", --"K23B Tactical"
		"amcar", --"Colt Model 733"
		"new_m4", --"Colt M4A1"
		"m16", --"Colt M16A4"
		"tecci", --"H&K 416C"
		"contraband", --"H&K 417 w/M203 GL"
		-- "contraband_m203", --"H&K 417 w/M203 GL"
		-- Assault Rifles --
		"galil", --"IMI Galil ARM"
		"s552", --"Swiss Arms SG 552-2"
		"g36", --"H&K G36KV"
		"ak5", --"Bofors Ak 5"
		"sub2000", --"Kel-tec SUB-2000"
		-- Bullpup Rifles --
		"aug", --"Steyr AUG A2"
		"famas", --"FAMAS F1"
		"l85a2", --"Enfield L85A2"
		"vhs", --"VHS-D2"
		"corgi", --"FN F2000"
		"komodo", --"IWI X95"
		-- AKs --
		"akm", --"Izhmash AKMS"
		"akm_gold", --"Golden AKMS"
		"ak74", --"Izhmash AKS-74"
		"asval", --"AS VAL"
		"akmsu", --"Izhmash AKMSU"
		"flint", --"Modern AK"
		-- Battle Rifles --
		"scar", --"FN SCAR-H STD"
		"fal", --"FN FAL"
		"g3", --"H&K G3A3"
		"new_m14", --"Springfield Armory M1A SOCOM 16"
		--"ching", --"Springfield Armory M1 Garand"
		-- Sniper Rifles --
		"model70", --"Winchester Model 70"
		"msr", --"Remington MSR"
		"r93", --"Blaser R93 LRS2"
		"desertfox", --"Desert Tech SRSA1"
		--"mosin", --"Mosin-Nagant M1907"
		--"winchester1874", --"Winchester Model 1873"
		"wa2000", --"Walther WA 2000"
		"tti", --"KAC SR-25"
		"siltstone", --"SVD Dragunov"
		-- Classic Shotties --
		--"boot", --"Winchester Model 1887"
		"serbu", --"Remington M870 Short-Barreled"
		"r870", --"Remington M870"
		"m37", --"Ithaca 37"
		"ksg", --"Kel-tec KSG"
		--"huntsman", --"Stoeger/IGA Coach"
		--"b682", --"CZ Redhead Deluxe"
		--"coach", --"Remington Exposed Hammer SxS"
		-- Auto Shotties --
		--"judge", --"Taurus Judge"
		"benelli", --"Benelli M4 Super 90"
		"spas12", --"Franchi SPAS-12"
		"saiga", --"Izhmash Saiga-12K"
		"aa12", --"MPS AA-12 CQB"
		--"rota", --"Crye Precision SIX12"
		--"striker", --"Sentinel Armsel Striker"
		"basset", --"CBRPS Saiga Spike X1S"
		-- LMGs --
		"rpk", --"Izhmash RPK"
		"hk21", --"H&K 21E"
		"mg42", --"MG-42"
		"m249", --"FN M249 Para"
		"par", --"FN M240B"
		-- Pistols --
		"sparrow", --"Jericho 941 RPL"
		"pl14", --"PL-14 Lebedev"
		"b92fs", --"Beretta 92FS Centurion"
		"packrat", --"H&K P30L"
		"legacy", --"H&K P7M13"
		"glock_18c", --"Glock 18C"
		"g26", --"Glock 26"
		"ppk", --"Walther PPK"
		"jowi", --"Akimbo Glock 26"
		"g22c", --"Glock 22C"
		"glock_17", --"Glock 17"
		"usp", --"USP Tactical .45"
		"p226", --"Sig-Sauer P226"
		"hs2000", --"SA XDM"
		"colt_1911", --"M1911 Lightweight Operator"
		--"peacemaker", --"Single Action Army Cavalry"
		"deagle", --"IMI Desert Eagle Mark XIX"
		--"new_raging_bull", --"Taurus Raging Bull .44 Magnum"
		--"mateba", --"Mateba 2006M"
		--"c96", --"Mauser C96"
		"lemming", --"FN Five-Seven"
		--"chinchilla", --"S&W Model 29"
		"breech", --"Luger P08"
		"shrew", --"M1911 Colt Defender"
		"czech", --"CZ automatic"
		"beer", --"Beretta 93r"
		"stech", --"BitterSweetLife"
		-- Specials --
		--"m134", --"M134 Minigun"
		"shuno", --"MG41"
		--"flamethrower_mk2", --"Flamethrower"
		--"system", --"Little Flamethrower"
		-- Grenade Launchers --
		--"gre_m79", --"SA M79 Grenade Launcher"
		--"china", --"China Lake Grenade Launcher"
		--"m32", --"MGL Mk 1S"
		"arbiter" --"H&K XM-25"
		--"rpg7", --"RPG-7"
		--"ray", --"M202 FLASH"
		--"slap", --"H&K M320"
	}
	for i, wep_id in ipairs(tact_rel) do
		self[wep_id].tactical_reload = 1
	end
	--Mostly all akimbo just comment those that should be disabled
	local tact_akimbo = {
		--Akimbo SMGs
		"x_hajk", --"Akimbo CZ 805 BREN A1"
		"x_polymer", --"Akimbo KRISS Vector"
		"x_m1928", --"Akimbo Thompson M1928A1"
		"x_schakal", --"Akimbo H&K UMP-45"
		"x_mp5", --"Akimbo H&K MP5A4"
		"x_sr2", --"Akimbo SR-2M Veresk"
		"x_sterling", --"Akimbo Sterling L2A1"
		"x_m45", --"Akimbo Carl Gustav M/45"
		"x_uzi", --"Akimbo IMI Uzi"
		"x_baka", --"Akimbo IMI Micro Uzi"
		"x_scorpion", --"Akimbo Scropion vz.61"
		"x_mp9", --"Akimbo B&T MP9"
		"x_mac10", --"Akimbo Ingram MAC-10"
		"x_cobray", --"Akimbo Cobray M11/9"
		"x_mp7", --"Akimbo H&K MP7A2"
		"x_p90", --"Akimbo FN P90 TR"
		"x_coal", --"Akimbo PP-19 Bizon"
		"x_tec9", --"Akimbo Intratec TEC-9"
		"x_erma", --"Akimbo MP40"
		"x_shepheard", --"Akimbo SIG-Sauer MPX"
		"x_olympic", --"Akimbo K23B Tactical"
		"x_akmsu", --"Akimbo Izhmash AKMSU"
		--Akimbo Auto Shotties --
		--"x_judge", --"Akimbo Taurus Judge"
		--"x_rota", --"Akimbo Crye Precision SIX12"
		"x_basset", --"Akimbo CBRPS Saiga Spike X1S"
		--Akimbo Pistols --
		"x_sparrow", --"Akimbo Jericho 941 RPL"
		"x_pl14", --"Akimbo PL-14 Lebedev"
		"x_b92fs", --"Akimbo Beretta 92FS Centurion"
		"x_packrat", --"Akimbo H&K P30L"
		"x_legacy", --"Akimbo H&K P7M13"
		"x_g18c", --"Akimbo Glock 18C"
		"x_ppk", --"Akimbo Walther PPK"
		"x_g22c", --"Akimbo Glock 22C"
		"x_g17", --"Akimbo Glock 17"
		"x_usp", --"Akimbo USP Tactical .45"
		"x_p226", --"Akimbo Sig-Sauer P226"
		"x_hs2000", --"Akimbo SA XDM"
		"x_1911", --"Akimbo M1911 Lightweight Operator"
		"x_deagle", --"Akimbo IMI Desert Eagle Mark XIX"
		--"x_rage", --"Akimbo Taurus Raging Bull .44 Magnum"
		--"x_2006m", --"Akimbo Mateba 2006M"
		--"x_c96", --"Akimbo Mauser C96"
		--"x_chinchilla", --"Akimbo S&W Model 29"
		"x_breech", --"Akimbo Luger P08"
		"x_shrew", --"Akimbo M1911 Colt Defender"
		"x_czech", --"Akimbo CZ automatic"
		"x_beer", --"Akimbo Beretta 93r"
		"x_stech", --"Akimbo BitterSweetLife"
	}
	for i, wep_id in ipairs(tact_akimbo) do
		self[wep_id].tactical_reload = 2
	end
end)